#!/bin/sh
#
# otsdaq_convert_config_to_table
# 	Script to convert User Data and User Database
#	from using 'configuration' to 'table'
#
#	The thinking is that table is more clear
#	especially considering the overloading of the word
#	for Configuration group
#
#	Created by rrivera and uplegger in February 2019
#


START_DIR=${PWD}

echo
echo
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Do not source this script, run it as 'otsdaq_convert_config_to_table'"
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t You must have USER_DATA and ARTDAQ_DATABASE_URI environment variables setup. They are usually setup when you setup otsdaq."
return  >/dev/null 2>&1 #return is used if script is sourced

echo
echo	
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Checking environment..."
		
if [[ "x$USER_DATA" == "x" ]]; then
	echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t USER_DATA environment variable must be setup. Is your ots instance setup?"
	exit
fi

TABLE_DIR=$USER_DATA/ConfigurationInfo
if [ ! -d $TABLE_DIR ]; then
	echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t TABLE_DIR=${TABLE_DIR} path does not exist. Is your ots instance setup? Perhaps you already did this conversion?"
	#exit
fi
	
NEW_TABLE_DIR=$USER_DATA/TableInfo
if [ -d $NEW_TABLE_DIR ]; then
	echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t NEW_TABLE_DIR=${NEW_TABLE_DIR} path already exists. Perhaps you already did this conversion?"
	#exit
fi

echo
echo

ARTDAQ_DATABASE_DIR=`echo ${ARTDAQ_DATABASE_URI}|sed 's|.*//|/|'`	


if [[ "x$ARTDAQ_DATABASE_DIR" == "x" ]]; then
	echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t ARTDAQ_DATABASE_URI environment variable must be setup. Is your ots instance setup?"
	exit
fi

if [ ! -d $ARTDAQ_DATABASE_DIR ]; then
	echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t ARTDAQ_DATABASE_URI environment variable must be setup. Is your ots instance setup?"
	exit
fi


echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t USER_DATA=${USER_DATA}"
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t TABLE_DIR=${TABLE_DIR}"
echo
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t ARTDAQ_DATABASE_URI=${ARTDAQ_DATABASE_URI}"
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t ARTDAQ_DATABASE_DIR=${ARTDAQ_DATABASE_DIR}"

###########
#=====================================
###########	USER DATA conversion
echo
echo
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Converting Config to Table for path USER_DATA..."

echo

#rename ConfigurationInfo/ to TableInfo/
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Renaming Table Info folder..."
mv $TABLE_DIR $NEW_TABLE_DIR

cd $NEW_TABLE_DIR

echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Renaming Table Info files..."
for f in *ConfigurationInfo.xml; do mv -n "$f" "${f/ConfigurationInfo.xml}TableInfo.xml"; done; 

mv ConfigurationInfo.xsd TableInfo.xsd

echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Modifying Table Info file content..."
sed -i s/Configuration/Table/g *ableInfo.x*
sed -i s/CONFIGURATION/TABLE/g *ableInfo.x*
sed -i s/configuration/table/g *ableInfo.x*
sed -i s/TheSupervisor/GatewaySupervisor/g *ableInfo.x*
sed -i s/OtsConfigurationWizard/WizardSupervisor/g *ableInfo.x*

echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Renaming Active Groups file..."
mv $USER_DATA/ServiceData/ActiveConfigurationGroups.cfg $USER_DATA/ServiceData/ActiveTableGroups.cfg

#convert TheSupervisor to GatewaySupervisor
mv TheSupervisorTableInfo.xml GatewaySupervisorTableInfo.xml
sed -i s/TheSupervisor/GatewaySupervisor/g GatewaySupervisorTableInfo.xml
sed -i s/THE_SUPERVISOR/GATEWAY_SUPERVISOR/g GatewaySupervisorTableInfo.xml


###########
#=====================================
###########	USER DATABASE conversion

echo
echo
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Converting Config to Table for path USER_DATA..."

echo

cd $ARTDAQ_DATABASE_DIR

echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Renaming Table database folders..."
for f in *Configuration; do mv -- "$f" "${f/Configuration}Table"; done;

#hide index from transformation
for f in *Table; do mv -n "$f/index.json" "$f/index.txt"; done; 

sed -i s/Configuration/Table/g *Table/*.json #*/ end C++ comment coloring
sed -i s/CONFIGURATION/TABLE/g *Table/*.json #*/ end C++ comment coloring
sed -i s/configuration/table/g *Table/*.json #*/ end C++ comment coloring
sed -i s/TheSupervisor/GatewaySupervisor/g *Table/*.json #*/ end C++ comment coloring
sed -i s/THE_SUPERVISOR/GATEWAY_SUPERVISOR/g *Table/*.json #*/ end C++ comment coloring
sed -i s/libSupervisor/libGatewaySupervisor/g *Table/*.json #*/ end C++ comment coloring
sed -i s/OtsConfigurationWizard/WizardSupervisor/g *Table/*.json #*/ end C++ comment coloring

#revert things that have gone too far!
sed -i s/TableGUI/ConfigurationGUI/g *Table/*.json #*/ end C++ comment coloring
sed -i s/TableSubset/ConfigurationSubset/g *Table/*.json #*/ end C++ comment coloring


#return index after transformation
for f in *Table; do mv -n "$f/index.txt" "$f/index.json"; done; 


#convert TheSupervisor to GatewaySupervisor
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Converting TheSupervisor Table to GatewaySupervisor..."
mv TheSupervisorTable GatewaySupervisorTable
sed -i s/TheSupervisor/GatewaySupervisor/g GatewaySupervisorTable/*.json #*/ end C++ comment coloring
sed -i s/THE_SUPERVISOR/GATEWAY_SUPERVISOR/g GatewaySupervisorTable/*.json #*/ end C++ comment coloring
sed -i s/libSupervisor/libGatewaySupervisor/g GatewaySupervisorTable/*.json #*/ end C++ comment coloring
sed -i s/OtsConfigurationWizard/WizardSupervisor/g GatewaySupervisorTable/*.json #*/ end C++ comment coloring

#do same thing for MetaData table
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Fixing Metadata Table..."
mv ConfigurationGroupMetadata TableGroupMetadata

#hide index from transformation
mv TableGroupMetadata/index.json TableGroupMetadata/index.txt

sed -i s/Configuration/Table/g TableGroupMetadata/*.json #*/ end C++ comment coloring
sed -i s/CONFIGURATION/TABLE/g TableGroupMetadata/*.json #*/ end C++ comment coloring
sed -i s/configuration/table/g TableGroupMetadata/*.json #*/ end C++ comment coloring

#revert things that have gone too far!
sed -i s/TableGUI/ConfigurationGUI/g TableGroupMetadata/*.json #*/ end C++ comment coloring


#return index after transformation
mv TableGroupMetadata/index.txt TableGroupMetadata/index.json



###########
#=====================================
###########	ConfigurationPlugin to TablePlugin conversion

echo
echo
echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Converting ConfigurationPlugin to TablePlugin for all repositories..."

echo

#for every repo
# look for ConfigurationPluginDataFormats
#	move folder to TablePluginDataFormats
#		Convert each .cc and .h to _table.cc
#			Search and replace class names in the .h .cc

REPO_DIR="$(find $MRB_SOURCE/* -maxdepth 1 -iname 'otsdaq*')"


for p in ${REPO_DIR[@]}; do
	if [ -d $p ]; then    
	if [ -d $p/ConfigurationPluginDataFormats ]; then
		echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Plugin directory $p/ConfigurationPluginDataFormats"
		
		cd $p/ConfigurationPluginDataFormats
		
		for f in *Configuration*.cc ; do mv $f ${f//configuration/table} ; done
		for f in *Configuration* ; do mv $f ${f//Configuration/Table} ; done
		
		sed -i s/Configuration/Table/g *Table*;
		sed -i s/CONFIGURATION/TABLE/g *Table*;
		sed -i s/configuration/table/g *Table*;
		sed -i s/TableInterface/ConfigurationInterface/g *Table*;
		sed -i s/TableTree/ConfigurationTree/g *Table*;
		sed -i s/TableManager/ConfigurationManager/g *Table*;
		sed -i s/TableGUITypeClassNames_/ConfigurationGUITypeClassNames_/g *Table*;
		sed -i s/FSSRDACsTable/FSSRDACsConfiguration/g *Table*;

		#revert things that have gone too far!
		sed -i s/MessageFacilityTables/MessageFacilityConfigurations/g *Table*;
		sed -i s/XDAQ_TABLE_DATA_PATH/XDAQ_CONFIGURATION_DATA_PATH/g *Table*;
		sed -i s/XDAQ_TABLE_XML/XDAQ_CONFIGURATION_XML/g *Table*;
		sed -i s/XMLTable-30/XMLConfiguration-30/g *Table*;
		sed -i s/TableGUI/ConfigurationGUI/g *Table*;
		sed -i s/TableSubset/ConfigurationSubset/g *Table*;
		
		
		sed -i s/"configuration"/"table"/g CMakeLists.txt;
		sed -i s/Configuration/Table/g CMakeLists.txt;
		sed -i s/TableInterface/ConfigurationInterface/g CMakeLists.txt;
		
		cd ..
		mv $p/ConfigurationPluginDataFormats $p/TablePluginDataFormats
	fi
	

	if [ -d $p/UserConfigurationDataFormats ]; then
		echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Plugin directory $p/UserConfigurationDataFormats"
		
		cd $p/UserConfigurationDataFormats
		
		for f in *Configuration*.cc ; do mv $f ${f//configuration/table} ; done
		for f in *Configuration* ; do mv $f ${f//Configuration/Table} ; done
		
		sed -i s/Configuration/Table/g *Table*;
		sed -i s/CONFIGURATION/TABLE/g *Table*;
		sed -i s/configuration/table/g *Table*;
		sed -i s/TableInterface/ConfigurationInterface/g *Table*;
		sed -i s/TableTree/ConfigurationTree/g *Table*;
		sed -i s/TableManager/ConfigurationManager/g *Table*;
		sed -i s/TableGUITypeClassNames_/ConfigurationGUITypeClassNames_/g *Table*;
		sed -i s/FSSRDACsTable/FSSRDACsConfiguration/g *Table*;

		#revert things that have gone too far!
		sed -i s/MessageFacilityTables/MessageFacilityConfigurations/g *Table*;
		sed -i s/XDAQ_TABLE_DATA_PATH/XDAQ_CONFIGURATION_DATA_PATH/g *Table*;
		sed -i s/XDAQ_TABLE_XML/XDAQ_CONFIGURATION_XML/g *Table*;
		sed -i s/XMLTable-30/XMLConfiguration-30/g *Table*;
		
		
		sed -i s/"configuration"/"table"/g CMakeLists.txt;
		sed -i s/Configuration/Table/g CMakeLists.txt;
		sed -i s/TableInterface/ConfigurationInterface/g CMakeLists.txt;
		
		cd ..
		mv $p/UserConfigurationDataFormats $p/UserTableDataFormats
	fi
	
	fi
done

###########
#=====================================
###########	Done

cd $START_DIR


echo -e `date +"%h%y %T"` "convert_config_to_table.sh [${LINENO}]  \t Done with conversion."


echo
echo
echo
echo