#!/bin/sh
#
# otsdaq_add_artdaq_tables
# 	Script to add artdaq tables to otsdaq (User Data table definitions)
#
#


START_DIR=${PWD}

echo
echo
echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t Do not source this script, run it as 'otsdaq_add_artdaq_tables'"
echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t You must have USER_DATA and ARTDAQ_DATABASE_URI environment variables setup. They are usually setup when you setup otsdaq."
return  >/dev/null 2>&1 #return is used if script is sourced

echo
echo	
echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t Checking environment..."
		
if [[ "x$USER_DATA" == "x" ]]; then
	echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t USER_DATA environment variable must be setup. Is your ots instance setup?"
	exit
fi
	
TABLE_DIR=$USER_DATA/TableInfo
if [ ! -d $TABLE_DIR ]; then
	echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t TABLE_DIR=${TABLE_DIR} path does not exists. Is your ots instance setup?"
	exit
fi

echo
echo

echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t Modifying core table file: ${USER_DATA}/ServiceData/CoreTableInfoNames.dat"
echo
echo
echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t Before:"
cat $USER_DATA/ServiceData/CoreTableInfoNames.dat

echo "ARTDAQ/*" >> $USER_DATA/ServiceData/CoreTableInfoNames.dat

echo
echo
echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t After:"
cat $USER_DATA/ServiceData/CoreTableInfoNames.dat

echo
echo

UpdateOTS.sh --tables

echo
echo

echo -e `date +"%h%y %T"` "add_artdaq_tables.sh [${LINENO}]  \t Done adding artdaq tables."

echo
echo
echo
echo