#!/bin/sh
#
# otsdaq_beautify_artdaq_tables
# 	Script to beautify artdaq tables in User Database and User Data
#
#


START_DIR=${PWD}

echo
echo
echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t Do not source this script, run it as 'otsdaq_beautify_artdaq_tables'"
echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t You must have USER_DATA and ARTDAQ_DATABASE_URI environment variables setup. They are usually setup when you setup otsdaq."
return  >/dev/null 2>&1 #return is used if script is sourced

echo
echo	
echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t Checking environment..."
		
if [[ "x$USER_DATA" == "x" ]]; then
	echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t USER_DATA environment variable must be setup. Is your ots instance setup?"
	exit
fi
	
TABLE_DIR=$USER_DATA/TableInfo
if [ ! -d $TABLE_DIR ]; then
	echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t TABLE_DIR=${TABLE_DIR} path does not exists. Is your ots instance setup?"
	exit
fi

echo
echo

ARTDAQ_DATABASE_DIR=`echo ${ARTDAQ_DATABASE_URI}|sed 's|.*//|/|'`	


if [[ "x$ARTDAQ_DATABASE_DIR" == "x" ]]; then
	echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t ARTDAQ_DATABASE_URI environment variable must be setup. Is your ots instance setup?"
	exit
fi

if [ ! -d $ARTDAQ_DATABASE_DIR ]; then
	echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t ARTDAQ_DATABASE_URI environment variable must be setup. Is your ots instance setup?"
	exit
fi


echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t USER_DATA=${USER_DATA}"
echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t TABLE_DIR=${TABLE_DIR}"
echo
echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t ARTDAQ_DATABASE_URI=${ARTDAQ_DATABASE_URI}"
echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t ARTDAQ_DATABASE_DIR=${ARTDAQ_DATABASE_DIR}"

###########
#=====================================
###########	USER DATA conversion
echo
echo
echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t Converting artdaq tables..."

echo

cd $TABLE_DIR

echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t Modifying Table Info file content..."
	    
				
		sed -i s/ApplicationGroupID/LinkToApplicationGroupID/g XDAQContextTableInfo.xml
		sed -i s/APPLICATION_GROUP_ID/LINK_TO_APPLICATION_GROUP_ID/g XDAQContextTableInfo.xml
		sed -i s/LinkToLinkToApplicationGroupID/LinkToApplicationGroupID/g XDAQContextTableInfo.xml
		sed -i s/LINK_TO_LINK_TO_APPLICATION_GROUP_ID/LINK_TO_APPLICATION_GROUP_ID/g XDAQContextTableInfo.xml	
		
		mv ARTDAQBuilderTableInfo.xml ARTDAQEventBuilderTableInfo.xml >/dev/null 2>&1
		sed -i s/ARTDAQBuilderTable/ARTDAQEventBuilderTable/g *ableInfo.x* 
		sed -i s/ARTDAQ_BUILDER_TABLE/ARTDAQ_EVENT_BUILDER_TABLE/g *ableInfo.x*	
		
		#fix first letter capitalization
		sed -i s/boardReader/BoardReader/g *ableInfo.x*	
		sed -i s/boardreader/BoardReader/g *ableInfo.x*	
		sed -i s/eventBuilder/EventBuilder/g *ableInfo.x*	
		sed -i s/eventbuilder/EventBuilder/g *ableInfo.x*	
		sed -i s/dataLogger/DataLogger/g *ableInfo.x*		
		sed -i s/datalogger/DataLogger/g *ableInfo.x*	
		sed -i s/dispatcher/Dispatcher/g *ableInfo.x*	
		sed -i s/monitor/Monitor/g *ableInfo.x*	
		sed -i s/routingMaster/RoutingMaster/g *ableInfo.x*	
		sed -i s/routingmaster/RoutingMaster/g *ableInfo.x*	
		
		#fix plurality of group ID
		sed -i s/BoardReadersGroupID/BoardReaderGroupID/g *ableInfo.x*	
		sed -i s/EventBuildersGroupID/EventBuilderGroupID/g *ableInfo.x*	
		sed -i s/DataLoggersGroupID/DataLoggerGroupID/g *ableInfo.x*	
		sed -i s/DispatchersGroupID/DispatcherGroupID/g *ableInfo.x*	
		sed -i s/MonitorsGroupID/MonitorGroupID/g *ableInfo.x*	
		sed -i s/RoutingMastersGroupID/RoutingMasterGroupID/g *ableInfo.x*	
		sed -i s/BOARD_READERS_GROUP_ID/BOARD_READER_GROUP_ID/g *ableInfo.x*	
		sed -i s/EVENT_BUILDERS_GROUP_ID/EVENT_BUILDER_GROUP_ID/g *ableInfo.x*	
		sed -i s/DATA_LOGGERS_GROUP_ID/DATA_LOGGER_GROUP_ID/g *ableInfo.x*	
		sed -i s/DISPATCHERS_GROUP_ID/DISPATCHER_GROUP_ID/g *ableInfo.x*	
		sed -i s/MONITORS_GROUP_ID/MONITOR_GROUP_ID/g *ableInfo.x*	
		sed -i s/ROUTING_MASTERS_GROUP_ID/ROUTING_MASTER_GROUP_ID/g *ableInfo.x*	
		
		#fix UID
		sed -i s/SupervisorUID/BoardReaderUID/g *BoardReader*ableInfo.x*	
		sed -i s/SupervisorUID/EventBuilderUID/g *EventBuilder*ableInfo.x*	
		sed -i s/SupervisorUID/DataLoggerUID/g *DataLogger*ableInfo.x*	
		sed -i s/SupervisorUID/DispatcherUID/g *Dispatcher*ableInfo.x*	
		#sed -i s/SupervisorUID/MonitorUID/g *Monitor*ableInfo.x*	
		sed -i s/SupervisorUID/RoutingMasterUID/g *Routing*ableInfo.x*	
		sed -i s/SUPERVISOR_UID/BOARD_READER_UID/g *BoardReader*ableInfo.x*	
		sed -i s/SUPERVISOR_UID/EVENT_BUILDER_UID/g *EventBuilder*ableInfo.x*	
		sed -i s/SUPERVISOR_UID/DATA_LOGGER_UID/g *DataLogger*ableInfo.x*	
		sed -i s/SUPERVISOR_UID/DISPATCHER_UID/g *Dispatcher*ableInfo.x*	
		#sed -i s/SUPERVISOR_UID/MONITOR_UID/g *Monitor*ableInfo.x*	
		sed -i s/SUPERVISOR_UID/ROUTING_MASTER_UID/g *Routing*ableInfo.x*	



###########
#=====================================
###########	USER DATABASE conversion

echo

cd $ARTDAQ_DATABASE_DIR

echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t Modifying Table database folders..."

		#convert XDAQ_Context table column	
		sed -i s/ApplicationGroupID/LinkToApplicationGroupID/g XDAQContextTable/*.json #*/ end C++ comment coloring
		sed -i s/APPLICATION_GROUP_ID/LINK_TO_APPLICATION_GROUP_ID/g XDAQContextTable/*.json #*/ end C++ comment coloring	
		sed -i s/LinkToLinkToApplicationGroupID/LinkToApplicationGroupID/g XDAQContextTable/*.json #*/ end C++ comment coloring
		sed -i s/LINK_TO_LINK_TO_APPLICATION_GROUP_ID/LINK_TO_APPLICATION_GROUP_ID/g XDAQContextTable/*.json #*/ end C++ comment coloring		
		
		mv ARTDAQBuilderTable ARTDAQEventBuilderTable >/dev/null 2>&1
		sed -i s/ARTDAQBuilderTable/ARTDAQEventBuilderTable/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/ARTDAQ_BUILDER_TABLE/ARTDAQ_EVENT_BUILDER_TABLE/g *Table/*.json #*/ end C++ comment coloring	
			
		#fix first letter capitalization
		sed -i s/boardReader/BoardReader/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/boardreader/BoardReader/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/eventBuilder/EventBuilder/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/eventbuilder/EventBuilder/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/dataLogger/DataLogger/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/datalogger/DataLogger/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/dispatcher/Dispatcher/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/monitor/Monitor/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/routingMaster/RoutingMaster/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/routingmaster/RoutingMaster/g *Table/*.json #*/ end C++ comment coloring
			
		#fix plurality of group ID
		sed -i s/BoardReadersGroupID/BoardReaderGroupID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/EventBuildersGroupID/EventBuilderGroupID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/DataLoggersGroupID/DataLoggerGroupID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/DispatchersGroupID/DispatcherGroupID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/MonitorsGroupID/MonitorGroupID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/RoutingMastersGroupID/RoutingMasterGroupID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/BOARD_READERS_GROUP_ID/BOARD_READER_GROUP_ID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/EVENT_BUILDERS_GROUP_ID/EVENT_BUILDER_GROUP_ID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/DATA_LOGGERS_GROUP_ID/DATA_LOGGER_GROUP_ID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/DISPATCHERS_GROUP_ID/DISPATCHER_GROUP_ID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/MONITORS_GROUP_ID/MONITOR_GROUP_ID/g *Table/*.json #*/ end C++ comment coloring
		sed -i s/ROUTING_MASTERS_GROUP_ID/ROUTING_MASTER_GROUP_ID/g *Table/*.json #*/ end C++ comment coloring

		#fix UID
		sed -i s/SupervisorUID/BoardReaderUID/g *BoardReader*Table/*.json #*/ end C++ comment coloring
		sed -i s/SupervisorUID/EventBuilderUID/g *EventBuilder*Table/*.json #*/ end C++ comment coloring
		sed -i s/SupervisorUID/DataLoggerUID/g *DataLogger*Table/*.json #*/ end C++ comment coloring
		sed -i s/SupervisorUID/DispatcherUID/g *Dispatcher*Table/*.json #*/ end C++ comment coloring
		#sed -i s/SupervisorUID/MonitorUID/g *Monitor*Table/*.json #*/ end C++ comment coloring
		sed -i s/SupervisorUID/RoutingMasterUID/g *Routing*Table/*.json #*/ end C++ comment coloring
		sed -i s/SUPERVISOR_UID/BOARD_READER_UID/g *BoardReader*Table/*.json #*/ end C++ comment coloring
		sed -i s/SUPERVISOR_UID/EVENT_BUILDER_UID/g *EventBuilder*Table/*.json #*/ end C++ comment coloring
		sed -i s/SUPERVISOR_UID/DATA_LOGGER_UID/g *DataLogger*Table/*.json #*/ end C++ comment coloring
		sed -i s/SUPERVISOR_UID/DISPATCHER_UID/g *Dispatcher*Table/*.json #*/ end C++ comment coloring
		#sed -i s/SUPERVISOR_UID/MONITOR_UID/g *Monitor*Table/*.json #*/ end C++ comment coloring
		sed -i s/SUPERVISOR_UID/ROUTING_MASTER_UID/g *Routing*Table/*.json #*/ end C++ comment coloring

#done!

cd $START_DIR


echo -e `date +"%h%y %T"` "beautify_artdaq_tables.sh [${LINENO}]  \t Done with conversion."


echo
echo
echo
echo